name: CI

permissions:
  contents: read

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production
      CI: true
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 22.x
          cache: npm

      - run: NODE_ENV='' npm ci --ignore-scripts

      - run: npm run typecheck
      - run: npm run lint -- --max-warnings=0
      - run: npm run build

      # Enforce Lighthouse budgets (source of truth: lighthouse/budgets.json)
      - name: Check Lighthouse budgets
        run: npm run lh:preview

      - name: Upload Lighthouse preview artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-preview
          path: |
            lighthouse/*.json
            lighthouse/*.html
            .lighthouse/**

      - run: npx playwright install --with-deps
      - run: npm run test:offline
