name: Secret scanning (Gitleaks)

on:
  pull_request:
  push:
    branches: [main]
  schedule:
    - cron: '7 2 * * 1' # Weekly (Mon 02:07 UTC)

permissions:
  contents: read
  pull-requests: read
  security-events: write

jobs:
  gitleaks:
    name: Gitleaks scan
    runs-on: ubuntu-latest
    # Skip scanning forked PRs to avoid permission issues, but run on internal PRs and other events
    if: ${{ github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository }}
    permissions:
      contents: read
      pull-requests: read
      security-events: write
    steps:
      - name: Checkout full history
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        with:
          fetch-depth: 0

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@ff98106e4c7b2bc287b24eaf42907196329070c7 # v2
        with:
          args: "--no-git --redact --report-format sarif --report-path gitleaks.sarif"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload SARIF to code scanning
        if: always()
        uses: github/codeql-action/upload-sarif@3c3833e0f8c1c83d449a7478aa59c036a9165498 # v3.29.11
        with:
          sarif_file: gitleaks.sarif
          category: gitleaks
        continue-on-error: true

      - name: Upload Gitleaks SARIF artifact
        if: always()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: gitleaks-sarif
          path: gitleaks.sarif
          if-no-files-found: ignore
          retention-days: 5
