name: Secret scanning (Gitleaks)

on:
  pull_request:
  push:
    branches: [main]
  schedule:
    - cron: '7 2 * * 1' # Weekly (Mon 02:07 UTC)

permissions:
  contents: read
  security-events: write

jobs:
  gitleaks:
    name: Gitleaks scan
    runs-on: ubuntu-latest
    # Skip scanning forked PRs to avoid permission issues, but run on internal PRs and other events
    if: ${{ github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository }}
    permissions:
      contents: read
      pull-requests: read
      security-events: write
    steps:
      - name: Checkout full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          args: "--no-git --redact --report-format sarif --report-path gitleaks.sarif"

      - name: Upload SARIF to code scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: gitleaks.sarif
          category: gitleaks
