name: Sync labels

on:
  push:
    branches: [main]
    paths:
      - '.github/labels.yml'
  workflow_dispatch:

permissions:
  contents: read
  issues: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Sync repository labels
        uses: micnncim/action-label-syncer@v1
        with:
          manifest: .github/labels.yml
          prune: true
          token: ${{ secrets.GITHUB_TOKEN }}
